
def count_DNA_symbols(dna_string):

    count_A = count_C = count_G = count_T = 0

    for symbol in dna_string:
        if symbol == 'A':
            count_A += 1
        elif symbol == 'C':
            count_C += 1
        elif symbol == 'G':
            count_G += 1
        elif symbol == 'T':
            count_T += 1

    return count_A, count_C, count_G, count_T


DNA_string = "TGACACACACGACATTCCCTATGGTCCGCGTGCCAATCGGTTGTTAGCGCCGTATCCCGGCTCAAGAAGACCTTGGCTGGAATGGGCGTTTACCTTAATGTTATCTGATCTGGATTGTAAACGGCCTCACGGCAGGCCCCACCCGTGCGCCGCACTGCAGCGTATATAAGACGGCCGGCACGGAGGGAGTGTGCGCCACCAGAAAGGCGTCCGTACCCACTCACTACTGTCGGGACTCCGGCTTAGGCCAATCCATGATGTTTATTACAAGCGCGTCCGGCTTTCCACTTTGGCTCGCCCGGTAGCTGCAGCTGATTGCTGGGCAGTTGCGGGGGAGTGTAATATACTAGATACCGAGGTGATGCCCCTCGGAGGGCTATGAGCATTACCGGTAGATGCGCAGGGCTACGGGTGAGACTGTAGCAGCCATACAAGCGAGTCACGTGGCTAAATGTCCCGCCAATGCTACGTTCGTCCGAACTGGGACGATAGAACAGAGGCGGTAACGATAGGTACGTATACCACTAGTCCCAAGCACTGACACTTGCAGTTTCCTCTCCCGTTAGCATAGGACTGCGCTTACCCCCATCTTAGTCATATTCCGTTGTGGCGGCCCCCAACCTCCTACTACACGCGAGCAGTTTAAATTATCAGAGCGCGTCACGTGCTACACGCATAAAGCATCCAACAACTCCGATTAACGCGGGGCCTGGCGACTCGGTCCTTCATTTCCAGAGTCGGAAGAGCGACGCGGGGGCACCAATTATGCACCCTTCGAAAATTCGCCCTCCTTCATCATGTAGCCTCGACTCGGTAGGATTAAGATGACTTATCGTTTATCGTACGTCAGTTAAAGCTTCACGTTACGCCAAACGTTACGGTTCGAGAATTCAGTCACGAGTCTACCTAATGTCAATGTTGCTGTTTAAATAATTATGGCGGGACGGGTCGGGCTGCCTTCGTACCGATTTTT"

DNA_symbol_counts = count_DNA_symbols(DNA_string)

print(DNA_symbol_counts[0], DNA_symbol_counts[1], DNA_symbol_counts[2], DNA_symbol_counts[3])

#       A   C   G   T
#output 220 269 253 231


