'''
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.
Return: The reverse complement sc of s.
'''

def reverse_complement(dna_string):

    reversed_dna = dna_string[::-1]

    complement_dict = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    reverse_complement_string = ''.join(complement_dict[base] for base in reversed_dna)

    return reverse_complement_string

dna_sequence = "CAGGCTTCGATAACTCCGCCAGAGTCCAGCGTTAGGTGAGGCAATTACCTTAGAAACTGGTATGTATTTCTCAGTGCTTATGTTACTGGGGTCTCATTGTATTGGTCTATGAAGACAGGGTTCTCCAGGTGCAAAGTCCACTCAGATAAGTGAATATACCATCCATACAGTTTCGGAGCGGCGCCAATCGGCGACCCTTTGGCACTGCGGTCTGAGATCTCTTAGTCCACGATTGGCCCCCCCCGTGAGGAGGAGCAATACAGGGCCGTGGCCCAGCCCGCTATTGCTCCAAATTGGCACCGTCCTATACTACCTGGTATGGTGAAGGGGACGAATTATGGCTGACATATCTTCTAATACTAAGGGCAGGCCTGACGCCAGATCCCTTAATCCGACAGAGATATCCTCTCATAGGGAAGAGGACTAGATCGAGCTAAACTTTGTTCAGGTCCCTTTCGTGTGAGTACCGGGCCACCCGCACTAACAGACGGTTTCCCGCCACGCGTTCTACGATTTGATACCGCAAATAATGGCTCTAGAGAAGACACCTGTCTTACAAGCCTCCCCGGCTCCCCAGTACGGGACGGTGTGCATGTTTCTTGCCTACTATCAATTGTTCTTTCAAGACTCTCTCAGACGGGGCTGAAACCTCAATCCGCTGCGTCTGTTACCATAAGTGTGACCAGGAGGGCCCTTGAACCATGTAAGTAGACGTGATCCATATCGCCGTATGCGCTTAAAACGGCATTTGGCAGGTAGCGTAGATCCAGGCCACACATTTCGAGGAGACGTATAGACCGTTAAAATATGTCAATACGTTCATGATGTATCTACATCTGCAGCACACATGCAAATGACTAAGACCCTG"
reverse_complement_sequence = reverse_complement(dna_sequence)

print(reverse_complement_sequence)
